# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 370113966379db11a0773ea93d45139ceebbcbd44e8dc3f0293e6abe0912de954692cd9534154c833b9accb4e89f10ae2e7c4028eba75c99ee2abb3c3c7576ac

test:
  secret_key_base: cb6cb0b227d4cabadae227507e2e127aeed9375bf46b22900298f2f5acfae4a6311294cfe2fdae543bbe5eb10495a2b0336229e8d5f18c53dd128de8b20a43d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
